import { IndustryConfig } from '../types';

export const INDUSTRY_CONFIGS: IndustryConfig[] = [
  {
    id: 'retail',
    name: 'Retail / General Store',
    description: 'General retail, supermarket, convenience store',
    icon: 'ShoppingBag',
    defaultUnit: 'PCS',
    defaultGstRate: 18,
    customFields: [
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'size', label: 'Size/Variant', type: 'text' },
    ],
    commonHsnCodes: [
      { code: '3304', description: 'Cosmetics & Toiletries' },
      { code: '3401', description: 'Soap & Cleaning' },
      { code: '6401', description: 'Footwear' },
      { code: '8471', description: 'Computing Machines' },
      { code: '9503', description: 'Toys & Games' },
    ],
  },
  {
    id: 'restaurant',
    name: 'Restaurant / Food Service',
    description: 'Restaurant, cafe, bakery, catering',
    icon: 'UtensilsCrossed',
    defaultUnit: 'NOS',
    defaultGstRate: 5,
    customFields: [
      { key: 'cuisine', label: 'Cuisine Type', type: 'select', options: ['North Indian', 'South Indian', 'Chinese', 'Continental', 'Fast Food', 'Beverages', 'Desserts'] },
      { key: 'servingSize', label: 'Serving Size', type: 'select', options: ['Half', 'Full', 'Small', 'Medium', 'Large'] },
      { key: 'isVeg', label: 'Veg/Non-Veg', type: 'select', options: ['Veg', 'Non-Veg', 'Egg'] },
    ],
    commonHsnCodes: [
      { code: '9963', description: 'Restaurant Services' },
      { code: '2106', description: 'Food Preparations' },
      { code: '2202', description: 'Beverages (non-alcoholic)' },
      { code: '1905', description: 'Bread & Bakery' },
      { code: '0402', description: 'Dairy Products' },
    ],
  },
  {
    id: 'pharmacy',
    name: 'Pharmacy / Medical',
    description: 'Pharmacy, medical store, health products',
    icon: 'Pill',
    defaultUnit: 'NOS',
    defaultGstRate: 12,
    customFields: [
      { key: 'batchNo', label: 'Batch Number', type: 'text', required: true },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date', required: true },
      { key: 'manufacturer', label: 'Manufacturer', type: 'text' },
      { key: 'composition', label: 'Composition/Salt', type: 'text' },
      { key: 'scheduleType', label: 'Schedule', type: 'select', options: ['OTC', 'Schedule H', 'Schedule H1', 'Schedule X'] },
    ],
    commonHsnCodes: [
      { code: '3004', description: 'Medicines (packed)' },
      { code: '3003', description: 'Medicines (bulk)' },
      { code: '3005', description: 'Surgical Dressings' },
      { code: '9018', description: 'Medical Instruments' },
      { code: '3006', description: 'Pharmaceutical Goods' },
    ],
  },
  {
    id: 'electronics',
    name: 'Electronics / IT',
    description: 'Electronics, computers, mobile, accessories',
    icon: 'Monitor',
    defaultUnit: 'NOS',
    defaultGstRate: 18,
    customFields: [
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'model', label: 'Model Number', type: 'text' },
      { key: 'serialNo', label: 'Serial Number', type: 'text' },
      { key: 'warranty', label: 'Warranty (months)', type: 'number' },
    ],
    commonHsnCodes: [
      { code: '8471', description: 'Computers & Laptops' },
      { code: '8517', description: 'Mobile Phones' },
      { code: '8528', description: 'Monitors & TVs' },
      { code: '8443', description: 'Printers' },
      { code: '8504', description: 'Power Supply / UPS' },
    ],
  },
  {
    id: 'textiles',
    name: 'Textiles / Garments',
    description: 'Clothing, fabric, fashion accessories',
    icon: 'Shirt',
    defaultUnit: 'PCS',
    defaultGstRate: 5,
    customFields: [
      { key: 'size', label: 'Size', type: 'select', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Free Size'] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'material', label: 'Material', type: 'text' },
      { key: 'brand', label: 'Brand', type: 'text' },
    ],
    commonHsnCodes: [
      { code: '6109', description: 'T-shirts & Vests' },
      { code: '6203', description: 'Men\'s Trousers/Shorts' },
      { code: '6204', description: 'Women\'s Dresses' },
      { code: '6205', description: 'Men\'s Shirts' },
      { code: '5208', description: 'Cotton Fabrics' },
    ],
  },
  {
    id: 'grocery',
    name: 'Grocery / FMCG',
    description: 'Grocery, daily essentials, FMCG products',
    icon: 'Apple',
    defaultUnit: 'KGS',
    defaultGstRate: 5,
    customFields: [
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'weight', label: 'Weight/Volume', type: 'text' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date' },
    ],
    commonHsnCodes: [
      { code: '1006', description: 'Rice' },
      { code: '1001', description: 'Wheat' },
      { code: '1507', description: 'Cooking Oil' },
      { code: '1701', description: 'Sugar' },
      { code: '0904', description: 'Spices' },
    ],
  },
  {
    id: 'hardware',
    name: 'Hardware / Building Materials',
    description: 'Hardware store, building materials, paints',
    icon: 'Wrench',
    defaultUnit: 'NOS',
    defaultGstRate: 18,
    customFields: [
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'material', label: 'Material Type', type: 'text' },
      { key: 'dimensions', label: 'Dimensions', type: 'text' },
    ],
    commonHsnCodes: [
      { code: '7318', description: 'Screws, Bolts, Nuts' },
      { code: '3209', description: 'Paints (water-based)' },
      { code: '7304', description: 'Iron/Steel Pipes' },
      { code: '6810', description: 'Cement Products' },
      { code: '8481', description: 'Taps, Valves, Fittings' },
    ],
  },
  {
    id: 'automotive',
    name: 'Automotive / Spare Parts',
    description: 'Auto parts, accessories, service center',
    icon: 'Car',
    defaultUnit: 'NOS',
    defaultGstRate: 28,
    customFields: [
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'vehicleType', label: 'Vehicle Type', type: 'select', options: ['Two-Wheeler', 'Three-Wheeler', 'Car', 'SUV', 'Truck', 'Bus', 'Universal'] },
      { key: 'partNumber', label: 'Part Number (OEM)', type: 'text' },
      { key: 'compatibility', label: 'Compatible Models', type: 'text' },
    ],
    commonHsnCodes: [
      { code: '8708', description: 'Motor Vehicle Parts' },
      { code: '4011', description: 'Tyres (new)' },
      { code: '8507', description: 'Batteries' },
      { code: '2710', description: 'Lubricant/Engine Oil' },
      { code: '8512', description: 'Lighting & Signaling' },
    ],
  },
  {
    id: 'custom',
    name: 'Custom Industry',
    description: 'Define your own industry-specific fields',
    icon: 'Settings',
    defaultUnit: 'NOS',
    defaultGstRate: 18,
    customFields: [],
    commonHsnCodes: [],
  },
];

export function getIndustryConfig(id: string): IndustryConfig {
  return INDUSTRY_CONFIGS.find(c => c.id === id) || INDUSTRY_CONFIGS[INDUSTRY_CONFIGS.length - 1];
}
