import { Invoice, BusinessProfile } from '../types';
import { formatNumber } from './gst';
import { format } from 'date-fns';

function triggerDownload(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadInvoiceAsText(invoice: Invoice, business: BusinessProfile | null) {
  const separator = '='.repeat(60);
  const lines: string[] = [];

  lines.push(separator);
  lines.push(invoice.type === 'sales' ? '                    TAX INVOICE' : '                 PURCHASE INVOICE');
  lines.push(separator);
  lines.push('');

  if (business) {
    lines.push(`Business: ${business.businessName}`);
    if (business.address) lines.push(`Address:  ${business.address}`);
    lines.push(`          ${[business.city, business.state, business.pincode].filter(Boolean).join(', ')}`);
    lines.push(`GSTIN:    ${business.gstin}`);
    if (business.phone) lines.push(`Phone:    ${business.phone}`);
    if (business.email) lines.push(`Email:    ${business.email}`);
  }

  lines.push('');
  lines.push('-'.repeat(60));
  lines.push(`Invoice #:     ${invoice.invoiceNumber}`);
  lines.push(`Date:          ${format(new Date(invoice.invoiceDate), 'dd MMM yyyy')}`);
  lines.push(`Due Date:      ${format(new Date(invoice.dueDate), 'dd MMM yyyy')}`);
  lines.push(`Status:        ${invoice.status.toUpperCase()}`);
  lines.push('-'.repeat(60));
  lines.push('');

  lines.push(`Bill To:       ${invoice.partyName}`);
  if (invoice.partyGstin) lines.push(`GSTIN:         ${invoice.partyGstin}`);
  lines.push(`Place of Supply: ${invoice.placeOfSupply}`);
  lines.push(`Supply Type:   ${invoice.isInterState ? 'Inter-State (IGST)' : 'Intra-State (CGST+SGST)'}`);
  lines.push('');
  lines.push('-'.repeat(60));
  lines.push('ITEMS');
  lines.push('-'.repeat(60));

  invoice.items.forEach((item, idx) => {
    lines.push(`${idx + 1}. ${item.description}${item.hsnCode ? ` (HSN: ${item.hsnCode})` : ''}`);
    lines.push(`   Qty: ${item.quantity} ${item.unit}  |  Rate: ${formatNumber(item.rate)}  |  Discount: ${item.discount}%`);
    lines.push(`   Taxable: ${formatNumber(item.taxableAmount)}  |  GST: ${item.gstRate}%`);
    if (invoice.isInterState) {
      lines.push(`   IGST: ${formatNumber(item.igstAmount)}  |  Total: ${formatNumber(item.totalAmount)}`);
    } else {
      lines.push(`   CGST: ${formatNumber(item.cgstAmount)}  |  SGST: ${formatNumber(item.sgstAmount)}  |  Total: ${formatNumber(item.totalAmount)}`);
    }
    lines.push('');
  });

  lines.push('-'.repeat(60));
  lines.push(`Subtotal:      ${formatNumber(invoice.subtotal)}`);
  if (invoice.isInterState) {
    lines.push(`IGST:          ${formatNumber(invoice.totalIgst)}`);
  } else {
    lines.push(`CGST:          ${formatNumber(invoice.totalCgst)}`);
    lines.push(`SGST:          ${formatNumber(invoice.totalSgst)}`);
  }
  lines.push(`Round Off:     ${formatNumber(invoice.roundOff)}`);
  lines.push(`GRAND TOTAL:   INR ${formatNumber(invoice.grandTotal)}`);
  lines.push(separator);

  if (business?.bankName) {
    lines.push('');
    lines.push('BANK DETAILS');
    lines.push(`Bank:     ${business.bankName}`);
    lines.push(`A/C No:   ${business.accountNumber}`);
    lines.push(`IFSC:     ${business.ifscCode}`);
  }

  if (invoice.notes) {
    lines.push('');
    lines.push(`Notes: ${invoice.notes}`);
  }

  lines.push('');
  lines.push('Generated by GST Filing App');

  const filename = `${invoice.invoiceNumber.replace(/\//g, '-')}.txt`;
  triggerDownload(lines.join('\n'), filename, 'text/plain');
}

export function downloadInvoicesCSV(invoices: Invoice[]) {
  const headers = [
    'Invoice #', 'Date', 'Type', 'Party', 'GSTIN', 'Place of Supply',
    'Inter-State', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total Tax',
    'Round Off', 'Grand Total', 'Status',
  ];

  const rows = invoices.map(inv => [
    inv.invoiceNumber,
    format(new Date(inv.invoiceDate), 'dd/MM/yyyy'),
    inv.type,
    `"${inv.partyName}"`,
    inv.partyGstin || '',
    `"${inv.placeOfSupply}"`,
    inv.isInterState ? 'Yes' : 'No',
    formatNumber(inv.subtotal),
    formatNumber(inv.totalCgst),
    formatNumber(inv.totalSgst),
    formatNumber(inv.totalIgst),
    formatNumber(inv.totalTax),
    formatNumber(inv.roundOff),
    formatNumber(inv.grandTotal),
    inv.status,
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const filename = `invoices-report-${format(new Date(), 'yyyy-MM-dd')}.csv`;
  triggerDownload(csv, filename, 'text/csv');
}

interface ReportRow {
  label: string;
  values: string[];
}

export function downloadReportCSV(title: string, headers: string[], rows: ReportRow[]) {
  const lines = [
    title,
    `Generated on: ${format(new Date(), 'dd MMM yyyy HH:mm')}`,
    '',
    headers.join(','),
    ...rows.map(r => [r.label, ...r.values].join(',')),
  ];

  const filename = `${title.toLowerCase().replace(/\s+/g, '-')}-${format(new Date(), 'yyyy-MM-dd')}.csv`;
  triggerDownload(lines.join('\n'), filename, 'text/csv');
}

export function downloadGSTReturnCSV(
  returnType: string,
  selectedMonth: string,
  invoices: Invoice[],
) {
  const headers = [
    'Invoice #', 'Date', 'Party GSTIN', 'Party Name', 'Taxable Value',
    'CGST', 'SGST', 'IGST', 'Total Tax', 'Invoice Value',
  ];

  const rows = invoices.map(inv => [
    inv.invoiceNumber,
    format(new Date(inv.invoiceDate), 'dd/MM/yyyy'),
    inv.partyGstin || '',
    `"${inv.partyName}"`,
    formatNumber(inv.subtotal),
    formatNumber(inv.totalCgst),
    formatNumber(inv.totalSgst),
    formatNumber(inv.totalIgst),
    formatNumber(inv.totalTax),
    formatNumber(inv.grandTotal),
  ]);

  const totals = [
    'TOTAL', '', '', '',
    formatNumber(invoices.reduce((s, i) => s + i.subtotal, 0)),
    formatNumber(invoices.reduce((s, i) => s + i.totalCgst, 0)),
    formatNumber(invoices.reduce((s, i) => s + i.totalSgst, 0)),
    formatNumber(invoices.reduce((s, i) => s + i.totalIgst, 0)),
    formatNumber(invoices.reduce((s, i) => s + i.totalTax, 0)),
    formatNumber(invoices.reduce((s, i) => s + i.grandTotal, 0)),
  ];

  const csv = [
    `${returnType} - ${format(new Date(selectedMonth + '-01'), 'MMMM yyyy')}`,
    `Generated on: ${format(new Date(), 'dd MMM yyyy HH:mm')}`,
    '',
    headers.join(','),
    ...rows.map(r => r.join(',')),
    totals.join(','),
  ].join('\n');

  const filename = `${returnType.toLowerCase()}-${selectedMonth}.csv`;
  triggerDownload(csv, filename, 'text/csv');
}
